distro:
	cjsify --output javascripts/audience.js --export Audience --root coffeescripts audience.coffee
	cjsify --minify --output javascripts/audience.min.js --export Audience --root coffeescripts audience.coffee
